-- 코드를 입력하세요
SELECT
        PRODUCT_CODE
        ,PRICE * TOTAL_SALES_AMOUNT AS SALES
FROM    PRODUCT P, (SELECT
        PRODUCT_ID
        ,SUM(SALES_AMOUNT) AS TOTAL_SALES_AMOUNT
FROM
        OFFLINE_SALE
GROUP BY PRODUCT_ID
) O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC;