-- 코드를 입력하세요
SELECT CASE WHEN 
            TO_CHAR(DATETIME,'HH24')  LIKE '09' THEN '9'
       ELSE TO_CHAR(DATETIME,'HH24') END AS HOUR
       ,COUNT(*) AS COUNT
FROM
        ANIMAL_OUTS
WHERE 
        TO_CHAR(DATETIME,'HH24:MI') BETWEEN '09:00' AND '19:59'
GROUP BY TO_CHAR(DATETIME,'HH24')
ORDER BY  TO_CHAR(DATETIME,'HH24');