-- 코드를 입력하세요
SELECT 
        CATEGORY
        ,SUM(SALES) AS TOTAL_SALES
FROM
        BOOK A, BOOK_SALES B
WHERE   1=1
AND
    A.BOOK_ID = B.BOOK_ID
AND 
    TO_CHAR(SALES_DATE,'YYYY-MM') = '2022-01'
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;
